### ISSUE TITLE
how to set env

### ISSUE THREAD

**Issue by mixserrm999** [richdenton/cresques#1]
how can i set env data?

**Comment by richdenton** [comment]
Hi @mixserrm999! Thanks for your interest in the project. First of all, you'll want to make a copy of `.env.example` and rename it `.env`. Fill in the database vars, generate a random token, and you should be all set. I'll be sure to write-up much better documentation when I get closer to a 1.0 release.

**Comment by mixserrm999** [comment]
Thx
