### ISSUE TITLE
just an engine?

### ISSUE THREAD

**Issue by mixserrm999** [richdenton/cresques#2]
.

**Comment by richdenton** [comment]
Yes, Cresques is backend only. I have a client built for demonstration and testing purposes, but it lacks polish. I plan on showcasing a feature complete frontend shortly after reaching the 1.0 milestone with the backend. That should be soon, so stay tuned!

**Comment by richdenton** [comment]
I've added an early version of a client to the project. It is not yet feature complete, but please follow along as I continue to develop it.
